version: "3.8"

services:
  x-to-telegram:
    build: .
    container_name: x-to-telegram
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./sent_posts.json:/app/sent_posts.json
      - ./config.py:/app/config.py
